server:
  domain: online-QA-community
  version: 1.0

mysql:
  host: 127.0.0.1
  port: 3306
  database: online_community
  username: root
  password: 268366
  charset: utf8mb4

redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  database: 3
