server:
  domain: online-QA-community
  version: 1.0

mysql:
  host: 43.138.199.12
  port: 13306
  database: online_community
  username: root
  password: 123456
  charset: utf8mb4

redis:
  host: 43.138.199.12
  port: 6379
  password: ""
  database: 3
